version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - threatintel_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - SECRET_KEY=your-secret-key-change-in-production
    depends_on:
      - mongodb
    networks:
      - threatintel_network

volumes:
  mongodb_data:

networks:
  threatintel_network:
    driver: bridge
